python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 96}' --model-name "seer.SEER" --model-hyper-params '{"batch_size": 64, "d_ff": 512, "d_model": 128, "d_score": 32, "dropout": 0.2, "e_layers": 1, "head_dropout": 0.1, "horizon": 96, "k": 2, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 30, "num_experts": 4, "patch_len": 16, "patience": 5, "score_threshold": 0.2, "seq_len": 96, "stride": 8}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/SEER"&

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 192}' --model-name "seer.SEER" --model-hyper-params '{"batch_size": 64, "d_ff": 512, "d_model": 128, "d_score": 32, "dropout": 0.2, "e_layers": 1, "head_dropout": 0.1, "horizon": 192, "k": 2, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 30, "num_experts": 8, "patch_len": 16, "patience": 5, "score_threshold": 0.2, "seq_len": 96, "stride": 8}' --gpus 1 --num-workers 1 --timeout 60000 --save-path "ETTm2/SEER"&

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 336}' --model-name "seer.SEER" --model-hyper-params '{"batch_size": 64, "d_ff": 512, "d_model": 128, "d_score": 32, "dropout": 0, "e_layers": 1, "head_dropout": 0.1, "horizon": 336, "k": 2, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 30, "num_experts": 8, "patch_len": 16, "patience": 5, "score_threshold": 0.2, "seq_len": 96, "stride": 8}' --gpus 2 --num-workers 1 --timeout 60000 --save-path "ETTm2/SEER"&

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 720}' --model-name "seer.SEER" --model-hyper-params '{"batch_size": 64, "d_ff": 512, "d_model": 128, "d_score": 32, "dropout": 0.2, "e_layers": 1, "head_dropout": 0.1, "horizon": 720, "k": 2, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 30, "num_experts": 8, "patch_len": 16, "patience": 5, "score_threshold": 0.5, "seq_len": 96, "stride": 8}' --gpus 3 --num-workers 1 --timeout 60000 --save-path "ETTm2/SEER"&



