python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 192}' --model-name "srsnet.SRSNet" --model-hyper-params '{"alpha": 3.5, "batch_size": 32, "d_model": 256, "dropout": 0.05, "head_dropout": 0.1, "head_mode": "linear", "horizon": 192, "lradj": "type1", "norm": true, "patch_len": 16, "patience": 10, "pos": false, "seq_len": 96, "stride": 16}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/SRSNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 336}' --model-name "srsnet.SRSNet" --model-hyper-params '{"alpha": 5.0, "batch_size": 32, "d_model": 256, "dropout": 0.05, "head_dropout": 0.1, "head_mode": "linear", "horizon": 336, "lradj": "type1", "norm": true, "patch_len": 24, "patience": 10, "pos": true, "seq_len": 96, "stride": 24}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/SRSNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 720}' --model-name "srsnet.SRSNet" --model-hyper-params '{"alpha": 3.5, "batch_size": 256, "d_model": 128, "dropout": 0.1, "head_dropout": 0.05, "head_mode": "linear", "horizon": 720, "lr": 0.001, "lradj": "type1", "norm": true, "patch_len": 24, "patience": 5, "pos": false, "seq_len": 96, "stride": 24}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/SRSNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 96}' --model-name "srsnet.SRSNet" --model-hyper-params '{"alpha": 3.5, "batch_size": 32, "d_model": 256, "dropout": 0.1, "head_dropout": 0.1, "head_mode": "linear", "horizon": 96, "lradj": "type1", "norm": true, "patch_len": 16, "patience": 5, "pos": false, "seq_len": 96, "stride": 16}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/SRSNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 192}' --model-name "srsnet.SRSNet" --model-hyper-params '{"batch_size": 32, "d_model": 256, "dropout": 0.1, "head_dropout": 0.1, "head_mode": "linear", "horizon": 192, "lr": 0.001, "lradj": "type1", "norm": true, "patch_len": 16, "patience": 10, "pos": true, "seq_len": 96, "stride": 16}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/SRSNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 336}' --model-name "srsnet.SRSNet" --model-hyper-params '{"batch_size": 32, "d_model": 256, "dropout": 0.1, "head_dropout": 0.1, "head_mode": "linear", "horizon": 336, "lr": 0.0001, "lradj": "type1", "norm": true, "patch_len": 24, "patience": 10, "pos": false, "seq_len": 96, "stride": 24}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/SRSNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 720}' --model-name "srsnet.SRSNet" --model-hyper-params '{"batch_size": 32, "d_model": 256, "dropout": 0.1, "head_dropout": 0.1, "head_mode": "linear", "horizon": 720, "lr": 0.0001, "lradj": "type1", "norm": true, "patch_len": 24, "patience": 10, "pos": true, "seq_len": 96, "stride": 24}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/SRSNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 96}' --model-name "srsnet.SRSNet" --model-hyper-params '{"batch_size": 32, "d_model": 64, "dropout": 0.1, "head_dropout": 0.1, "head_mode": "linear", "horizon": 96, "lr": 0.0001, "lradj": "type1", "norm": true, "patch_len": 24, "patience": 10, "pos": false, "seq_len": 96, "stride": 24}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/SRSNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 192}' --model-name "srsnet.SRSNet" --model-hyper-params '{"batch_size": 64, "d_model": 256, "dropout": 0.05, "head_dropout": 0.1, "head_mode": "mlp", "horizon": 192, "loss": "MSE", "lr": 0.001, "lradj": "type1", "norm": true, "patch_len": 16, "patience": 5, "seq_len": 96, "stride": 16}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/SRSNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 336}' --model-name "srsnet.SRSNet" --model-hyper-params '{"batch_size": 64, "d_model": 128, "dropout": 0.05, "head_dropout": 0.05, "head_mode": "mlp", "horizon": 336, "loss": "MSE", "lr": 0.001, "lradj": "type1", "norm": true, "patch_len": 16, "patience": 5, "seq_len": 96, "stride": 16}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/SRSNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 720}' --model-name "srsnet.SRSNet" --model-hyper-params '{"batch_size": 64, "d_model": 256, "dropout": 0.01, "head_dropout": 0.05, "head_mode": "linear", "horizon": 720, "loss": "MSE", "lr": 0.001, "lradj": "type1", "norm": true, "patch_len": 24, "patience": 10, "seq_len": 96, "stride": 24}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/SRSNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 96}' --model-name "srsnet.SRSNet" --model-hyper-params '{"batch_size": 64, "d_model": 256, "dropout": 0.05, "head_dropout": 0.1, "head_mode": "mlp", "horizon": 96, "loss": "MSE", "lr": 0.001, "lradj": "type1", "norm": true, "patch_len": 16, "patience": 5, "seq_len": 96, "stride": 16}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/SRSNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 192}' --model-name "srsnet.SRSNet" --model-hyper-params '{"batch_size": 32, "d_model": 128, "dropout": 0.0, "head_dropout": 0.05, "head_mode": "linear", "horizon": 192, "loss": "MSE", "lr": 0.0001, "lradj": "type1", "norm": true, "patch_len": 12, "patience": 10, "pos": false, "seq_len": 96, "stride": 12}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/SRSNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 336}' --model-name "srsnet.SRSNet" --model-hyper-params '{"batch_size": 64, "d_model": 128, "dropout": 0.0, "head_dropout": 0.05, "head_mode": "linear", "horizon": 336, "loss": "MSE", "lr": 0.0001, "lradj": "type1", "norm": true, "patch_len": 16, "patience": 10, "pos": false, "seq_len": 96, "stride": 16}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/SRSNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 720}' --model-name "srsnet.SRSNet" --model-hyper-params '{"batch_size": 64, "d_model": 128, "dropout": 0.0, "head_dropout": 0.05, "head_mode": "linear", "horizon": 720, "loss": "MSE", "lr": 0.0001, "lradj": "type1", "norm": true, "patch_len": 16, "patience": 10, "pos": true, "seq_len": 96, "stride": 16}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/SRSNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 96}' --model-name "srsnet.SRSNet" --model-hyper-params '{"batch_size": 32, "d_model": 256, "dropout": 0.0, "head_dropout": 0.1, "head_mode": "linear", "horizon": 96, "loss": "MSE", "lr": 0.0001, "lradj": "type1", "norm": true, "patch_len": 12, "patience": 10, "pos": true, "seq_len": 96, "stride": 12}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/SRSNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 192}' --model-name "srsnet.SRSNet" --model-hyper-params '{"batch_size": 64, "d_model": 128, "dropout": 0.0, "head_dropout": 0.05, "head_mode": "mlp", "horizon": 192, "loss": "MSE", "lr": 0.0001, "lradj": "type1", "norm": true, "patch_len": 24, "patience": 5, "seq_len": 96, "stride": 24}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/SRSNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 336}' --model-name "srsnet.SRSNet" --model-hyper-params '{"batch_size": 64, "d_model": 128, "dropout": 0.0, "head_dropout": 0.1, "head_mode": "mlp", "horizon": 336, "loss": "MSE", "lr": 0.0001, "lradj": "type1", "norm": true, "patch_len": 24, "patience": 5, "seq_len": 96, "stride": 24}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/SRSNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 720}' --model-name "srsnet.SRSNet" --model-hyper-params '{"batch_size": 64, "d_model": 128, "dropout": 0.0, "head_dropout": 0.05, "head_mode": "mlp", "horizon": 720, "loss": "MSE", "lr": 0.0001, "lradj": "type1", "norm": true, "patch_len": 16, "patience": 5, "seq_len": 96, "stride": 16}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/SRSNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 96}' --model-name "srsnet.SRSNet" --model-hyper-params '{"batch_size": 64, "d_model": 128, "dropout": 0.0, "head_dropout": 0.05, "head_mode": "mlp", "horizon": 96, "loss": "MSE", "lr": 0.001, "lradj": "type1", "norm": true, "patch_len": 24, "patience": 5, "seq_len": 96, "stride": 24}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/SRSNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar.csv" --strategy-args '{"horizon": 192}' --model-name "srsnet.SRSNet" --model-hyper-params '{"batch_size": 64, "d_model": 128, "dropout": 0.0, "head_dropout": 0.05, "head_mode": "mlp", "horizon": 192, "loss": "MSE", "lr": 0.005, "lradj": "type1", "norm": true, "patch_len": 24, "patience": 5, "seq_len": 96, "stride": 24}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Solar/SRSNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar.csv" --strategy-args '{"horizon": 336}' --model-name "srsnet.SRSNet" --model-hyper-params '{"batch_size": 64, "d_model": 128, "dropout": 0.0, "head_dropout": 0.05, "head_mode": "mlp", "horizon": 336, "loss": "MSE", "lr": 0.005, "lradj": "type1", "norm": true, "patch_len": 24, "patience": 5, "seq_len": 96, "stride": 24}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Solar/SRSNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar.csv" --strategy-args '{"horizon": 720}' --model-name "srsnet.SRSNet" --model-hyper-params '{"batch_size": 64, "d_model": 256, "dropout": 0.0, "head_dropout": 0.05, "head_mode": "mlp", "horizon": 720, "loss": "MSE", "lr": 0.001, "lradj": "type1", "norm": true, "patch_len": 16, "patience": 5, "seq_len": 96, "stride": 16}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Solar/SRSNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar.csv" --strategy-args '{"horizon": 96}' --model-name "srsnet.SRSNet" --model-hyper-params '{"batch_size": 64, "d_model": 128, "dropout": 0.0, "head_dropout": 0.05, "head_mode": "mlp", "horizon": 96, "loss": "MSE", "lr": 0.005, "lradj": "type1", "norm": true, "patch_len": 24, "patience": 5, "seq_len": 96, "stride": 24}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Solar/SRSNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 192}' --model-name "srsnet.SRSNet" --model-hyper-params '{"batch_size": 16, "d_model": 512, "dropout": 0.0, "head_dropout": 0.05, "head_mode": "mlp", "horizon": 192, "loss": "MSE", "lr": 0.0002, "lradj": "type3", "norm": true, "patch_len": 16, "patience": 5, "seq_len": 96, "stride": 16}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/SRSNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 336}' --model-name "srsnet.SRSNet" --model-hyper-params '{"batch_size": 16, "d_model": 512, "dropout": 0.0, "head_dropout": 0.05, "head_mode": "mlp", "horizon": 336, "loss": "MSE", "lr": 0.0001, "lradj": "type3", "norm": true, "patch_len": 16, "patience": 5, "seq_len": 96, "stride": 16}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/SRSNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 720}' --model-name "srsnet.SRSNet" --model-hyper-params '{"batch_size": 32, "d_model": 512, "dropout": 0.0, "head_dropout": 0.05, "head_mode": "mlp", "horizon": 720, "loss": "MSE", "lr": 0.0005, "lradj": "type1", "norm": true, "patch_len": 16, "patience": 5, "seq_len": 96, "stride": 16}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/SRSNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 96}' --model-name "srsnet.SRSNet" --model-hyper-params '{"batch_size": 16, "d_model": 512, "dropout": 0.0, "head_dropout": 0.05, "head_mode": "mlp", "horizon": 96, "loss": "MSE", "lr": 0.0002, "lradj": "type3", "norm": true, "patch_len": 16, "patience": 5, "seq_len": 96, "stride": 16}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/SRSNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 192}' --model-name "srsnet.SRSNet" --model-hyper-params '{"batch_size": 64, "d_model": 128, "dropout": 0.0, "head_dropout": 0.05, "head_mode": "mlp", "horizon": 192, "loss": "MSE", "lr": 0.001, "lradj": "type1", "norm": true, "patch_len": 24, "patience": 5, "seq_len": 96, "stride": 24}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/SRSNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 336}' --model-name "srsnet.SRSNet" --model-hyper-params '{"batch_size": 64, "d_model": 128, "dropout": 0.0, "head_dropout": 0.05, "head_mode": "mlp", "horizon": 336, "loss": "MSE", "lr": 0.001, "lradj": "type1", "norm": true, "patch_len": 24, "patience": 5, "seq_len": 96, "stride": 24}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/SRSNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 720}' --model-name "srsnet.SRSNet" --model-hyper-params '{"batch_size": 64, "d_model": 128, "dropout": 0.0, "head_dropout": 0.05, "head_mode": "mlp", "horizon": 720, "loss": "MSE", "lr": 0.001, "lradj": "type1", "norm": true, "patch_len": 24, "patience": 5, "seq_len": 96, "stride": 24}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/SRSNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 96}' --model-name "srsnet.SRSNet" --model-hyper-params '{"batch_size": 64, "d_model": 128, "dropout": 0.0, "head_dropout": 0.05, "head_mode": "mlp", "horizon": 96, "loss": "MSE", "lr": 0.001, "lradj": "type1", "norm": true, "patch_len": 16, "patience": 5, "seq_len": 96, "stride": 16}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/SRSNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 192}' --model-name "srsnet.SRSNet" --model-hyper-params '{"batch_size": 64, "d_model": 256, "dropout": 0, "head_dropout": 0.05, "head_mode": "mlp", "hidden_size": 256, "horizon": 192, "loss": "MSE", "lr": 0.005, "lradj": "type3", "norm": true, "patch_len": 24, "patience": 5, "seq_len": 96, "stride": 24}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/SRSNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 336}' --model-name "srsnet.SRSNet" --model-hyper-params '{"batch_size": 64, "d_model": 256, "dropout": 0, "head_dropout": 0.05, "head_mode": "mlp", "hidden_size": 128, "horizon": 336, "loss": "MSE", "lr": 0.005, "lradj": "type3", "norm": true, "patch_len": 24, "patience": 5, "seq_len": 96, "stride": 24}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/SRSNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 720}' --model-name "srsnet.SRSNet" --model-hyper-params '{"batch_size": 64, "d_model": 128, "dropout": 0, "head_dropout": 0.05, "head_mode": "mlp", "hidden_size": 256, "horizon": 720, "loss": "MSE", "lr": 0.005, "lradj": "type3", "norm": true, "patch_len": 24, "patience": 5, "seq_len": 96, "stride": 24}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/SRSNet"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 96}' --model-name "srsnet.SRSNet" --model-hyper-params '{"batch_size": 64, "d_model": 256, "dropout": 0, "head_dropout": 0.05, "head_mode": "mlp", "hidden_size": 256, "horizon": 96, "loss": "MSE", "lr": 0.005, "lradj": "type3", "norm": true, "patch_len": 24, "patience": 5, "seq_len": 96, "stride": 24}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/SRSNet"

