python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 96}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size": 256, "lr": 0.0001, "lradj": "sigmoid", "horizon": 96, "norm": true, "seq_len": 96}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/xPatch"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 192}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size": 256, "lr": 0.0001, "lradj": "sigmoid", "horizon": 192, "norm": true, "seq_len": 96}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/xPatch"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 336}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size": 256, "lr": 0.0001, "lradj": "sigmoid", "horizon": 336, "norm": true, "seq_len": 96}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/xPatch"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 720}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size": 256, "lr": 0.0001, "lradj": "sigmoid", "horizon": 720, "norm": true, "seq_len": 96}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/xPatch"


python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 96}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size": 256, "lr": 0.0001, "lradj": "sigmoid", "horizon": 96, "norm": true, "seq_len": 96}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/xPatch"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 192}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size": 256, "lr": 0.0001, "lradj": "sigmoid", "horizon": 192, "norm": true, "seq_len": 96}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/xPatch"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 336}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size": 256, "lr": 0.0001, "lradj": "sigmoid", "horizon": 336, "norm": true, "seq_len": 96}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/xPatch"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 720}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size": 256, "lr": 0.0001, "lradj": "sigmoid", "horizon": 720, "norm": true, "seq_len": 96}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/xPatch"


python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 96}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size": 256, "lr": 0.0001, "lradj": "sigmoid", "horizon": 96, "norm": true, "seq_len": 96}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/xPatch"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 192}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size": 256, "lr": 0.0001, "lradj": "sigmoid", "horizon": 192, "norm": true, "seq_len": 96}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/xPatch"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 336}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size": 256, "lr": 0.0001, "lradj": "sigmoid", "horizon": 336, "norm": true, "seq_len": 96}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/xPatch"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 720}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size": 256, "lr": 0.0001, "lradj": "sigmoid", "horizon": 720, "norm": true, "seq_len": 96}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/xPatch"



python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 96}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size": 256, "lr": 0.0001, "lradj": "sigmoid", "horizon": 96, "norm": true, "seq_len": 96}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/xPatch"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 192}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size": 256, "lr": 0.0001, "lradj": "sigmoid", "horizon": 192, "norm": true, "seq_len": 96}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/xPatch"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 336}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size": 256, "lr": 0.0001, "lradj": "sigmoid", "horizon": 336, "norm": true, "seq_len": 96}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/xPatch"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 720}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size": 256, "lr": 0.0001, "lradj": "sigmoid", "horizon": 720, "norm": true, "seq_len": 96}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/xPatch"



python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 96}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size": 256, "lr": 0.0001, "lradj": "sigmoid", "horizon": 96, "norm": true, "seq_len": 96}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/xPatch"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 192}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size": 256, "lr": 0.0001, "lradj": "sigmoid", "horizon": 192, "norm": true, "seq_len": 96}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/xPatch"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 336}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size": 256, "lr": 0.0001, "lradj": "sigmoid", "horizon": 336, "norm": true, "seq_len": 96}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/xPatch"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 720}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size": 256, "lr": 0.0001, "lradj": "sigmoid", "horizon": 720, "norm": true, "seq_len": 96}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/xPatch"



python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 96}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size": 96, "lr": 0.005, "lradj": "sigmoid", "horizon": 96, "norm": true, "seq_len": 96}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/xPatch"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 192}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size": 96, "lr": 0.005, "lradj": "sigmoid", "horizon": 192, "norm": true, "seq_len": 96}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/xPatch"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 336}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size": 96, "lr": 0.005, "lradj": "sigmoid", "horizon": 336, "norm": true, "seq_len": 96}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/xPatch"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 720}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size": 96, "lr": 0.005, "lradj": "sigmoid", "horizon": 720, "norm": true, "seq_len": 96}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/xPatch"



python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 96}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size": 256, "lr": 0.005, "lradj": "sigmoid", "horizon": 96, "norm": true, "seq_len": 96}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/xPatch"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 192}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size": 256, "lr": 0.005, "lradj": "sigmoid", "horizon": 192, "norm": true, "seq_len": 96}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/xPatch"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 336}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size": 256, "lr": 0.005, "lradj": "sigmoid", "horizon": 336, "norm": true, "seq_len": 96}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/xPatch"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 720}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size": 256, "lr": 0.005, "lradj": "sigmoid", "horizon": 720, "norm": true, "seq_len": 96}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/xPatch"



python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar.csv" --strategy-args '{"horizon": 96}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size": 256, "lr": 0.005, "lradj": "sigmoid", "horizon": 96, "norm": true, "patience": 3, "seq_len": 96}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Solar/xPatch"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar.csv" --strategy-args '{"horizon": 192}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size": 256, "lr": 0.005, "lradj": "sigmoid", "horizon": 192, "norm": true, "patience": 3, "seq_len": 96}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Solar/xPatch"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar.csv" --strategy-args '{"horizon": 336}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size": 256, "lr": 0.005, "lradj": "sigmoid", "horizon": 336, "norm": true, "patience": 3, "seq_len": 96}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Solar/xPatch"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar.csv" --strategy-args '{"horizon": 720}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size": 256, "lr": 0.005, "lradj": "sigmoid", "horizon": 720, "norm": true, "patience": 3, "seq_len": 96}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Solar/xPatch"




python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 96}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size": 32, "lr": 0.0001, "lradj": "type1", "ma_type": "reg", "patience": 3, "num_epochs": 10, "horizon": 96, "norm": true, "seq_len": 96}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/xPatch"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 192}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size": 32, "lr": 0.0001, "lradj": "type1", "ma_type": "reg", "patience": 3, "num_epochs": 10, "horizon": 192, "norm": true, "seq_len": 96}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/xPatch"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 336}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size": 32, "lr": 0.0001, "lradj": "type1", "ma_type": "reg", "patience": 3, "num_epochs": 10, "horizon": 336, "norm": true, "seq_len": 96}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/xPatch"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 720}' --model-name "xpatch.xPatch" --model-hyper-params '{"batch_size": 32, "lr": 0.0001, "lradj": "type1", "ma_type": "reg", "patience": 3, "num_epochs": 10, "horizon": 720, "norm": true, "seq_len": 96}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/xPatch"
